name: Deploy Node App to Docker Hub using github context and Env concept..

on:
  push:
    branches:
      - main
      - 'feature/**'

env:
  DOCKER_REPO: ayaddala/my-node-app
  IMAGE_NAME: my-node-app

jobs:
  docker-deploy:
    runs-on: Ashok-self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Set dynamic image tag
        id: set_tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's#refs/heads/##' | tr / -)
            echo "TAG=${BRANCH_NAME}" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: AWS ECR Push
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 173003893026.dkr.ecr.ap-south-1.amazonaws.com
          docker build -t ayaddala/docker .
          docker tag ayaddala/docker:latest 173003893026.dkr.ecr.ap-south-1.amazonaws.com/ayaddala/docker:latest
          docker push 173003893026.dkr.ecr.ap-south-1.amazonaws.com/ayaddala/docker:latest


      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.TAG }}

  deploy:
     needs: docker-deploy
     runs-on: Ashok-self-hosted
     steps:
      - name: Compose up
        run: |
          docker compose up -d
          docker ps

      - name: Output result
        run: echo " Image pushed as $DOCKER_REPO:$TAG"
