name: Deploy Node App to Docker Hub using github context and Env concept...

on:
  push:
    branches:
      - main
      - 'feature/**'

env:
  DOCKER_REPO: ayaddala/my-node-app
  IMAGE_NAME: my-node-app

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Set dynamic image tag
        id: set_tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's#refs/heads/##' | tr / -)
            echo "TAG=${BRANCH_NAME}" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.TAG }}

      - name: Output result
        run: echo " Image pushed as $DOCKER_REPO:$TAG"
